In [12]:
import pandas as pd
#get_dumies

In [13]:
data = pd.read_csv("datasets/ford.csv", encoding='latin-1')
data.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [14]:
data = pd.get_dummies(data, columns = ['fuelType'])

# data['is_urban'] = (data['Residence_type'] == 'Urban' ).astype(int)

data

,model,year,price,transmission,mileage,tax,mpg,engineSize,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,Fiesta,2017,12000,Automatic,15944,150,57.7,1.0,0,0,0,0,1
1,Focus,2018,14000,Manual,9083,150,57.7,1.0,0,0,0,0,1
2,Focus,2017,13000,Manual,12456,150,57.7,1.0,0,0,0,0,1
3,Fiesta,2019,17500,Manual,10460,145,40.3,1.5,0,0,0,0,1
4,Fiesta,2019,16500,Automatic,1482,145,48.7,1.0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,150,47.1,1.4,0,0,0,0,1
17962,B-MAX,2014,7499,Manual,40700,30,57.7,1.0,0,0,0,0,1
17963,Focus,2015,9999,Manual,7010,20,67.3,1.6,1,0,0,0,0
17964,KA,2018,8299,Manual,5007,145,57.7,1.2,0,0,0,0,1
17965,Focus,2015,8299,Manual,5007,22,57.7,1.0,0,0,0,0,1

In [15]:
def csvAdapted(dataset, modifyColumns, dropColumns):
    data = pd.read_csv(dataset, encoding='latin-1')
    columns = data.columns
    
    for index in modifyColumns:
        name = columns[index]
        value = list( data[name].unique() )
        data[name] = data[name].map( dict( zip( value,  [i for i in range( len(value) ) ] ) ) )

    data = data.drop([columns[index] for index in dropColumns ], axis=1)

    print(data.head())

    return data.to_numpy()

data = csvAdapted("datasets/ford.csv", [i for i in range(0, 8) if not i in [1, 2, 4, 6, 7, 8] ], [])

   model  year  price  transmission  mileage  fuelType  tax   mpg  engineSize
0      0  2017  12000             0    15944         0  150  57.7         1.0
1      1  2018  14000             1     9083         0  150  57.7         1.0
2      1  2017  13000             1    12456         0  150  57.7         1.0
3      0  2019  17500             1    10460         0  145  40.3         1.5
4      0  2019  16500             0     1482         0  145  48.7         1.0

In [16]:
data = pd.read_csv("dataset-tortuga.csv", encoding='latin-1')

UniqueData = [
    [ list( data.PROFILE.unique() ), "PROFILE" ],
]

DictData = []

for value, name in UniqueData:
    DictData.append(  [ dict( zip( value,  [i for i in range( len(value) ) ] ) ), name ])

newDataSet = pd.DataFrame()

newDataSet["HOURS_DATASCIENCE"] = data['HOURS_DATASCIENCE']
newDataSet["HOURS_BACKEND"] = data['HOURS_BACKEND']
newDataSet["HOURS_FRONTEND"] = data['HOURS_FRONTEND'] 
newDataSet["NUM_COURSES_BEGINNER_DATASCIENCE"] = data['NUM_COURSES_BEGINNER_DATASCIENCE'] 
newDataSet["NUM_COURSES_BEGINNER_BACKEND"] = data['NUM_COURSES_BEGINNER_BACKEND'] 
newDataSet["NUM_COURSES_BEGINNER_FRONTEND"] = data['NUM_COURSES_BEGINNER_FRONTEND'] 
newDataSet["NUM_COURSES_ADVANCED_DATASCIENCE"] = data['NUM_COURSES_ADVANCED_DATASCIENCE'] 
newDataSet["NUM_COURSES_ADVANCED_BACKEND"] = data['NUM_COURSES_ADVANCED_BACKEND'] 
newDataSet["NUM_COURSES_ADVANCED_FRONTEND"] = data['NUM_COURSES_ADVANCED_FRONTEND'] 
newDataSet["AVG_SCORE_DATASCIENCE"] = data['AVG_SCORE_DATASCIENCE'] 
newDataSet["AVG_SCORE_BACKEND"] = data['AVG_SCORE_BACKEND'] 
newDataSet["AVG_SCORE_FRONTEND"] = data['AVG_SCORE_FRONTEND'] 

for value, name in DictData:
    newDataSet[name] = data[name].map(value)

newDataSet = newDataSet.dropna()
newDataSet.to_csv("dataset-tortuga-2.csv", index=False)

newDataSet

FileNotFoundError: [Errno 2] No such file or directory: 'dataset-tortuga.csv'

In [ ]:
#Optimizado
def csvAdapted(path, modifyColumns, dropColumns):
    data = pd.read_csv(path, encoding='latin-1')
    columns = data.columns
    
    for index in modifyColumns:
        name = columns[index]
        value = list( data[name].unique() )
        data[name] = data[name].map( dict( zip( value,  [i for i in range( len(value) ) ] ) ) )

    data = data.drop([columns[index] for index in dropColumns ], axis=1)

    print(data.head())

    return data.to_numpy()

data = csvAdapted("laptop_price.csv", [i for i in range(0, 12) if not i in [4] ], [0] )
data